# Generated by Django 2.2.1 on 2019-05-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='电话'),
        ),
    ]
